version: '3.8'

services:
  db:
    image: 'postgres'
    env_file:
      - db.env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - alectrion-user-network

  user_api:
    depends_on:
      - db
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - alectrion-user-network
      - alectrion-network
    ports:
      - 4001:4001
    command: bash -c "yarn && yarn migration:run && yarn dev"

networks:
  alectrion-user-network:
  alectrion-network:
    external: true
